version: 1.2
workflows:
 - name: sphl_lims_file_prep
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_sphl_lims_file_prep.wdl
 - name: sphl_lims_file_gen
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_sphl_lims_file_gen.wdl
 - name: genomic_cluster_analysis
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_genomic_cluster_analysis.wdl
 - name: amplicon_coverage
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_amplicon_coverage.wdl
